[package]
name = "chem-eng-real-time-process-control-simulator"
version = "0.0.1"
edition = "2021"
<<<<<<< HEAD
=======
license = "Apache-2.0"
description = "Process Control Library (Chemical Engineering) with real time transfer function simulators"
homepage = "https://github.com/theodoreOnzGit/chem-eng-real-time-process-control-simulator"
repository ="https://github.com/theodoreOnzGit/chem-eng-real-time-process-control-simulator"
readme = "README.md"
categories = ["science"]
>>>>>>> main

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
csv = "1.3.0"
thiserror = "1.0.50"
uom = "0.35.0"

[[bin]]
name = "library_demo"
path = "src/main.rs"

[lib]
name = "chem_eng_real_time_process_control_simulator"
path = "src/lib/lib.rs"



# fast and small binary
[profile.release]
opt-level = 2 

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
